# Generated by Django 3.1.5 on 2021-01-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UploadedImage',
        ),
    ]
